del ..\Rendering\*.o
del ..\Arrangement\*.o
del ..\Layout\*.o
del ..\Presentation\*.o
del ..\Evaluation\*.o
del ..\Main\*.o
del ..\Common\*.o
del ..\Helium\lvm\src\lib\asm\*.o
del ..\Helium\lvm\src\lib\common\ghc\*.o
del ..\Helium\lvm\src\lib\common\*.o
del ..\Helium\lvm\src\lib\core\*.o
del ..\Helium\lvm\src\lib\lvm\*.o
del ..\Helium\lvm\src\lib\parsec\*.o
del ..\Helium\helium\*.o
del ..\Helium\helium\demo\*.o
del ..\Helium\helium\parsec\*.o
del ..\Helium\helium\parser\*.o
del ..\Helium\helium\staticanalysis\*.o
del ..\Helium\helium\uha\*.o
del ..\Helium\helium\uhaToCore\*.o
del ..\Helium\helium\utils\*.o

del ..\Rendering\*.hi
del ..\Arrangement\*.hi
del ..\Layout\*.hi
del ..\Presentation\*.hi
del ..\Evaluation\*.hi
del ..\Main\*.hi
del ..\Common\*.hi
del ..\Helium\lvm\src\lib\asm\*.hi
del ..\Helium\lvm\src\lib\common\ghc\*.hi
del ..\Helium\lvm\src\lib\common\*.hi
del ..\Helium\lvm\src\lib\core\*.hi
del ..\Helium\lvm\src\lib\lvm\*.hi
del ..\Helium\lvm\src\lib\parsec\*.hi
del ..\Helium\helium\*.hi
del ..\Helium\helium\demo\*.hi
del ..\Helium\helium\parsec\*.hi
del ..\Helium\helium\parser\*.hi
del ..\Helium\helium\staticanalysis\*.hi
del ..\Helium\helium\uha\*.hi
del ..\Helium\helium\uhaToCore\*.hi
del ..\Helium\helium\utils\*.hi
